spring:
  application:
    name: microservice-eureka-ha
  profiles: qyw_1

server:
  port: 8761
eureka:
  instance:
    hostname: qyw_1
  client:
    service-url:
        defaultZone: http://qyw_2:8762/eureka/
