server:
  port: 8801

spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
