server:
  port: 8030
spring:
  application:
    name: service-hysrtix-turbine
eureka:
  client:
    service-url:
     defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: service-consumer-user
  cluster-name-expression: "'default'"