server:
    port: 8084
spring:
  application:
    name: service-consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  compression:
    request:
      min-request-size: 4096
      mime-types: application/json